name: speech_to_text_example
description: Demonstrates how to use the speech_to_text plugin.
version: 1.1.0
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  bloc: ^4.0.0
  equatable: ^1.1.1
  hydrated_bloc: ^4.0.0
  polygon_clipper: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  speech_to_text:
    path: ../

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
  - assets/sounds/speech_to_text_listening.m4r
  - assets/sounds/speech_to_text_cancel.m4r
  - assets/sounds/speech_to_text_stop.m4r
